---
name: Github Action for LaTeX
description: GitHub Action to compile LaTeX documents
author: Cheng XU
inputs:
  texlive_version:
    description: Tex Live version to be used
    default: latest
  debian_release:
    description: Debian debian_release to be used
    default: trixie
  root_file:
    description: The root LaTeX file to be compiled
    required: true
  glob_root_file:
    description: Interpret the root_file input as bash glob pattern
    default: "false"
  working_directory:
    description: The working directory for this action
    default: .
  work_in_root_file_dir:
    description: Change directory into each root file's directory before compiling each documents
    default: "false"
  continue_on_error:
    description: Continuing to build document even with LaTeX build errors
    default: "false"
  compiler:
    description: The LaTeX engine to be invoked
    default: latexmk
  args:
    description: Extra arguments to be passed to the LaTeX engine
    default: -pdf -file-line-error -halt-on-error -interaction=nonstopmode
  extra_packages:
    description: "[Deprecated] Install extra packages by tlmgr"
    default: ""
  extra_system_packages:
    description: Install extra packages by apt
    default: ""
  extra_fonts:
    description: Install extra .ttf/.otf fonts.
    default: ""
  pre_compile:
    description: Arbitrary bash codes to be executed before compiling LaTeX documents
    default: ""
  post_compile:
    description: Arbitrary bash codes to be executed after compiling LaTeX documents
    default: ""
  latexmk_shell_escape:
    default: "false"
    description: Instruct latexmk to enable --shell-escape
  latexmk_use_lualatex:
    description: Instruct latexmk to use LuaLaTeX
    default: "false"
  latexmk_use_xelatex:
    description: Instruct latexmk to use XeLaTeX
    default: "false"
runs:
  using: composite
  steps:
    - shell: bash
      run: >
        docker run --rm
        -v "${PWD}":/github/workspace
        -v "${GITHUB_ACTION_PATH}/entrypoint.sh":/entrypoint.sh
        -w /github/workspace
        --entrypoint "/entrypoint.sh"
        zydou/texlive:${{ inputs.texlive_version }}-${{ inputs.debian_release }}
        "${{ inputs.root_file }}"
        "${{ inputs.glob_root_file }}"
        "${{ inputs.working_directory }}"
        "${{ inputs.work_in_root_file_dir }}"
        "${{ inputs.continue_on_error }}"
        "${{ inputs.compiler }}"
        "${{ inputs.args }}"
        "${{ inputs.extra_packages }}"
        "${{ inputs.extra_system_packages }}"
        "${{ inputs.extra_fonts }}"
        "${{ inputs.pre_compile }}"
        "${{ inputs.post_compile }}"
        "${{ inputs.latexmk_shell_escape }}"
        "${{ inputs.latexmk_use_lualatex }}"
        "${{ inputs.latexmk_use_xelatex }}"
branding:
  icon: book
  color: blue
