---
name: Github Action for LaTeX
description: GitHub Action to compile LaTeX documents
author: Cheng XU
inputs:
  texlive_version:
    description: Tex Live version to be used
    default: latest
  debian_release:
    description: Debian debian_release to be used
    default: trixie
  root_file:
    description: The root LaTeX file to be compiled
    required: true
  working_directory:
    description: The working directory for this action
    default: .
  work_in_root_file_dir:
    description: Change directory into each root file's directory before compiling each documents
    default: "false"
  continue_on_error:
    description: Continuing to build document even with LaTeX build errors
    default: "false"
  compiler:
    description: The LaTeX engine to be invoked
    default: latexmk
  args:
    description: Extra arguments to be passed to the LaTeX engine
    default: -pdf -file-line-error -halt-on-error -interaction=nonstopmode
  extra_system_packages:
    description: Install extra packages by apt-get
    default: ""
  extra_fonts:
    description: Install extra .ttf/.otf fonts.
    default: ""
  pre_compile:
    description: Arbitrary bash codes to be executed before compiling LaTeX documents
    default: ""
  post_compile:
    description: Arbitrary bash codes to be executed after compiling LaTeX documents
    default: ""
  latexmk_shell_escape:
    description: Instruct latexmk to enable --shell-escape
    default: "false"
  latexmk_use_lualatex:
    description: Instruct latexmk to use LuaLaTeX
    default: "false"
  latexmk_use_xelatex:
    description: Instruct latexmk to use XeLaTeX
    default: "false"

runs:
  using: composite
  steps:
    - shell: bash
      run: >
        docker run --rm
        -e "ACTIONS_CACHE_URL"
        -e "ACTIONS_RUNTIME_TOKEN"
        -e "ACTIONS_RUNTIME_URL"
        -e "GITHUB_ACTION_REF"
        -e "GITHUB_ACTION_REPOSITORY"
        -e "GITHUB_ACTION"
        -e "GITHUB_ACTOR_ID"
        -e "GITHUB_ACTOR"
        -e "GITHUB_API_URL"
        -e "GITHUB_BASE_REF"
        -e "GITHUB_ENV"
        -e "GITHUB_EVENT_NAME"
        -e "GITHUB_EVENT_PATH"
        -e "GITHUB_GRAPHQL_URL"
        -e "GITHUB_HEAD_REF"
        -e "GITHUB_JOB"
        -e "GITHUB_OUTPUT"
        -e "GITHUB_PATH"
        -e "GITHUB_REF_NAME"
        -e "GITHUB_REF_PROTECTED"
        -e "GITHUB_REF_TYPE"
        -e "GITHUB_REF"
        -e "GITHUB_REPOSITORY_ID"
        -e "GITHUB_REPOSITORY_OWNER_ID"
        -e "GITHUB_REPOSITORY_OWNER"
        -e "GITHUB_REPOSITORY"
        -e "GITHUB_RETENTION_DAYS"
        -e "GITHUB_RUN_ATTEMPT"
        -e "GITHUB_RUN_ID"
        -e "GITHUB_RUN_NUMBER"
        -e "GITHUB_SERVER_URL"
        -e "GITHUB_SHA"
        -e "GITHUB_STATE"
        -e "GITHUB_STEP_SUMMARY"
        -e "GITHUB_TRIGGERING_ACTOR"
        -e "GITHUB_WORKFLOW_REF"
        -e "GITHUB_WORKFLOW_SHA"
        -e "GITHUB_WORKFLOW"
        -e "GITHUB_WORKSPACE"
        -e "HOME"
        -e "RUNNER_ARCH"
        -e "RUNNER_ENVIRONMENT"
        -e "RUNNER_NAME"
        -e "RUNNER_OS"
        -e "RUNNER_TEMP"
        -e "RUNNER_TOOL_CACHE"
        -e "RUNNER_WORKSPACE"
        -e "TEXINPUTS"
        -e CI=true
        -e GITHUB_ACTIONS=true
        -v "/var/run/docker.sock":"/var/run/docker.sock"
        -v "$HOME:$HOME"
        -v "$GITHUB_ENV:$GITHUB_ENV"
        -v "$GITHUB_OUTPUT:$GITHUB_OUTPUT"
        -v "$GITHUB_STEP_SUMMARY:$GITHUB_STEP_SUMMARY"
        -v "$GITHUB_PATH:$GITHUB_PATH"
        -v "$GITHUB_WORKSPACE:$GITHUB_WORKSPACE"
        -v "$GITHUB_ACTION_PATH/entrypoint.sh":/entrypoint.sh
        -w "$GITHUB_WORKSPACE"
        --entrypoint "/entrypoint.sh"
        zydou/texlive:${{ inputs.texlive_version }}-${{ inputs.debian_release }}
        "${{ inputs.root_file }}"
        "${{ inputs.working_directory }}"
        "${{ inputs.work_in_root_file_dir }}"
        "${{ inputs.continue_on_error }}"
        "${{ inputs.compiler }}"
        "${{ inputs.args }}"
        "${{ inputs.extra_system_packages }}"
        "${{ inputs.extra_fonts }}"
        "${{ inputs.pre_compile }}"
        "${{ inputs.post_compile }}"
        "${{ inputs.latexmk_shell_escape }}"
        "${{ inputs.latexmk_use_lualatex }}"
        "${{ inputs.latexmk_use_xelatex }}"
branding:
  icon: book
  color: blue
